name: CI
on: [push, pull_request]

jobs:
    eslint:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - name: Install Packages
              run: npm install
            - name: Run ESLint script
              run: npm run lint
